"""Contracts package for Nayom-Automation."""
from .business import Business
from .maps import MapsSearchRequest, MapsSearchResult
from .website import (
    Page,
    PageHeading,
    PageLink,
    PageImage,
    PageForm,
    PageFormField,
    PageButton,
    PageMetadata,
    PageContent,
    PageError,
    StructuredData,
    WebsiteCollectionRequest,
    WebsiteCollectionResult,
)
from .intelligence import (
    ServiceProduct,
    SocialLink,
    ContactIntelligence,
    CallToAction,
    BusinessProfile,
    BrandAndContentIntelligence,
    DesignAndUXAnalysis,
    TechnicalAndSEOAnalysis,
    RedesignRecommendations,
    TemplateRecommendation,
    TokenUsage,
    IntelligenceMetadata,
    WebsiteIntelligence,
)
from .template import (
    TemplateMetadata,
    TemplateValidationResult,
    TemplateRegistryIndex,
    NayomTemplateManifest,
    TemplateInspectionResult,
    TemplateImportResult,
)
from .generator import (
    WebsiteGenerationRequest,
    WebsiteGenerationResult,
)
from .deployment import (
    ProviderStatus,
    DeploymentRequest,
    DeploymentResult,
)
from .email import (
    OutreachEmailDraft,
    OutreachEmail,
    EmailGenerationRequest,
    SenderProviderStatus,
    EmailDeliveryRequest,
    EmailDeliveryResult,
)
from .orchestrator import (
    StageStatus,
    PIPELINE_STAGES,
    StageExecution,
    BusinessRunState,
    PipelineRunConfig,
    PipelineSummary,
    PipelineRunState,
)
from .events import PipelineEvent, EventLevel

__all__ = [
    "Business",
    "MapsSearchRequest",
    "MapsSearchResult",
    "Page",
    "PageHeading",
    "PageLink",
    "PageImage",
    "PageForm",
    "PageFormField",
    "PageButton",
    "PageMetadata",
    "PageContent",
    "PageError",
    "StructuredData",
    "WebsiteCollectionRequest",
    "WebsiteCollectionResult",
    "ServiceProduct",
    "SocialLink",
    "ContactIntelligence",
    "CallToAction",
    "BusinessProfile",
    "BrandAndContentIntelligence",
    "DesignAndUXAnalysis",
    "TechnicalAndSEOAnalysis",
    "RedesignRecommendations",
    "TemplateRecommendation",
    "TokenUsage",
    "IntelligenceMetadata",
    "WebsiteIntelligence",
    "TemplateMetadata",
    "TemplateValidationResult",
    "TemplateRegistryIndex",
    "WebsiteGenerationRequest",
    "WebsiteGenerationResult",
    "ProviderStatus",
    "DeploymentRequest",
    "DeploymentResult",
    "OutreachEmailDraft",
    "OutreachEmail",
    "EmailGenerationRequest",
    "SenderProviderStatus",
    "EmailDeliveryRequest",
    "EmailDeliveryResult",
    "StageStatus",
    "PIPELINE_STAGES",
    "StageExecution",
    "BusinessRunState",
    "PipelineRunConfig",
    "PipelineSummary",
    "PipelineRunState",
    "PipelineEvent",
    "EventLevel",
]
